apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
  namespace: tomcat
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: dfgdf:mobile-10-23
        name: mysql
        ports:
        - containerPort: 443
