apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tomcat
  name: tomcat
  namespace: default
spec:
  replicas: 12
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - image: registry-vpc.cn-beijing.aliyuncs.com/wuu-docker/independent-gzt:v0.1
        name: nginx
        ports:
        - containerPort: 443
